// Canonical identity of one complete resolved Draft program.
//
// Individual resolution pins prove that exact generated bytes were selected for
// fresh typed obligations. The resolved-program digest binds those local facts
// to the complete selected package graph, exact resolved Draft and assembly
// bytes, target/ABI/assembly profile, and compiler semantics identity. Provider
// provenance is deliberately absent: exact accepted Draft source, rather than
// the tool which proposed it, is the program input. Judgment evidence can bind
// to the resulting digest independently.
//
// Physical paths, FileId values, syntax IDs, build-directory names, and host
// enumeration order are excluded. The function performs no I/O: callers must
// pass the already loaded resolved graph and source manager. Foreign libraries,
// artifacts, and runtime assets enter through exact
// content-tree pins. Host toolchains and SDKs are build configuration.
// Relevant specification: docs/specification/03-agent-synthesis.md section 10.

#pragma once

#include "base/sha256.h"
#include "compile/configuration.h"
#include "elaborator/resolution.h"
#include "source/source.h"
#include "target/profile.h"
#include "workspace/workspace.h"

#include <string_view>

namespace draft {

// Hashes fields with explicit lengths and collection counts under the versioned
// `draft.resolved-program.v6` domain. The selected root is hashed explicitly;
// graph package/file order is already
// canonical; external inputs and pins are sorted inside this operation so
// caller vector order cannot affect the result.
[[nodiscard]] Sha256Digest hash_resolved_program(
    const SourceManager &sources,
    const WorkspaceGraph &graph,
    const TargetProfile &target,
    const ResolutionManifest &manifest,
    std::string_view compiler_content_identity,
    const CompileConfiguration &configuration = CompileConfiguration{});

} // namespace draft
