# Provider-free resolved-program consumer contract.
#
# The checked-in acceptance workspace is copied because target revalidation,
# validation evidence, and native intermediates are intentional command
# outputs. A `codex` sentinel shadows any real installation while retaining the
# platform environment needed by matching LLVM and system tools. Revalidation
# first selects the host's target-qualified
# manifest using only existing generated bytes; check, build, test, and bench
# must then consume that complete program without executing the sentinel. The
# test also rejects any persistent cache hierarchy created by repeated commands.

if(NOT DEFINED DRAFTC OR NOT DEFINED SOURCE_WORKSPACE OR
   NOT DEFINED TEST_ROOT OR NOT DEFINED TARGET_SELECTOR)
  message(FATAL_ERROR
    "DRAFTC, SOURCE_WORKSPACE, TEST_ROOT, and TARGET_SELECTOR are required")
endif()

file(REMOVE_RECURSE "${TEST_ROOT}")
file(MAKE_DIRECTORY "${TEST_ROOT}")
file(COPY "${SOURCE_WORKSPACE}" DESTINATION "${TEST_ROOT}")
get_filename_component(workspace_name "${SOURCE_WORKSPACE}" NAME)
set(workspace "${TEST_ROOT}/${workspace_name}")
set(package "${workspace}/app")

# The sentinel makes accidental provider execution observable without hiding
# the platform tools required by native validation.
set(provider_bin "${TEST_ROOT}/provider-must-not-run")
set(provider_marker "${TEST_ROOT}/provider-was-invoked")
file(MAKE_DIRECTORY "${provider_bin}")
file(WRITE "${provider_bin}/codex"
  "#!/bin/sh\nprintf 'invoked\\n' > '${provider_marker}'\nexit 97\n")
file(CHMOD "${provider_bin}/codex"
  PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ GROUP_EXECUTE
    WORLD_READ WORLD_EXECUTE)
set(provider_free_path "${provider_bin}:$ENV{PATH}")

function(run_provider_free result_name)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "PATH=${provider_free_path}"
      "${DRAFTC}" ${ARGN}
    RESULT_VARIABLE command_status
    OUTPUT_VARIABLE command_stdout
    ERROR_VARIABLE command_stderr
  )
  if(NOT command_status EQUAL 0)
    string(JOIN " " rendered_command ${ARGN})
    message(FATAL_ERROR
      "provider-free ${rendered_command} failed (${command_status})\n"
      "stdout:\n${command_stdout}\nstderr:\n${command_stderr}")
  endif()
  set(${result_name} "${command_stdout}" PARENT_SCOPE)
endfunction()

# A resolution manifest selects one target. Revalidation is itself
# provider-free and lets the same committed generated source qualify the copied
# fixture for either supported native host before the four consumer commands.
run_provider_free(resolve_stdout
  resolve "${workspace}" --root app --revalidate --target "${TARGET_SELECTOR}")
if(NOT resolve_stdout MATCHES "resolved 4 synthesis sites")
  message(FATAL_ERROR "revalidation lost its resolution report: ${resolve_stdout}")
endif()

run_provider_free(check_stdout
  check "${workspace}" --root app --target "${TARGET_SELECTOR}")
if(NOT check_stdout MATCHES "checked package graph rooted at app")
  message(FATAL_ERROR "check lost its success report: ${check_stdout}")
endif()

set(assembly_output "${TEST_ROOT}/assembly")
run_provider_free(build_stdout
  build "${workspace}" --root app --target "${TARGET_SELECTOR}"
  --kind assembly -o "${assembly_output}")
if(NOT build_stdout MATCHES "built ${assembly_output}")
  message(FATAL_ERROR "build lost its success report: ${build_stdout}")
endif()

run_provider_free(test_stdout
  test "${workspace}" --root app --target "${TARGET_SELECTOR}")
if(NOT test_stdout MATCHES "test passed: 1 selected procedures")
  message(FATAL_ERROR "test lost its success report: ${test_stdout}")
endif()

run_provider_free(bench_stdout
  bench "${workspace}" --root app --target "${TARGET_SELECTOR}")
if(NOT bench_stdout MATCHES "benchmark passed: 1 selected procedures")
  message(FATAL_ERROR "bench lost its success report: ${bench_stdout}")
endif()

if(EXISTS "${provider_marker}")
  message(FATAL_ERROR "a provider-free consumer invoked Codex")
endif()
file(GLOB validation_evidence "${package}/.draft/evidence/*.json")
if(NOT validation_evidence)
  message(FATAL_ERROR "provider-free validation did not publish evidence")
endif()
set(has_linked_llvm_evidence FALSE)
foreach(evidence_file IN LISTS validation_evidence)
  file(READ "${evidence_file}" evidence)
  if(evidence MATCHES "\"toolchain\": \"linked-llvm-version:22\\.")
    set(has_linked_llvm_evidence TRUE)
  endif()
endforeach()
if(NOT has_linked_llvm_evidence)
  message(FATAL_ERROR
    "fresh validation evidence does not identify linked LLVM 22")
endif()
if(EXISTS "${workspace}/.draft/cache" OR
   EXISTS "${package}/.draft/cache")
  message(FATAL_ERROR "repeated commands created a persistent compiler cache")
endif()

file(REMOVE_RECURSE "${TEST_ROOT}")
